repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: trailing-whitespace
- repo: https://github.com/prettier/prettier
  rev: "1.9.1"
  hooks:
    - id: prettier
