import { Type } from "typebox";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { existsSync } from "node:fs";
import { cwd as cwdFn } from "node:process";
import { dirname } from "node:path";
import { LspClient } from "./transport";
import { SERVER_CONFIGS } from "./servers";
import type { Diagnostic, Location, LspState, ServerConfig } from "./protocol";
import { configForFile, diagnosticsDetails, errorResult, findAncestorWithMarker, findEnclosingSymbol, findExecutable, findWorkspaceRoot, flattenSymbols, formatDiagnostics, formatLocation, formatSymbol, formatSymbols, isInsidePath, linePreview, locationsDetails, rangeToDetails, relativePath, resolvePath, symbolKindName, toLspPosition, uriToPath } from "./utils";

export function registerLspExtension(pi: ExtensionAPI) {
  const clients = new Map<string, LspClient>();
  const startingClients = new Map<string, Promise<LspClient>>();
  const workspaceRoots = new Map<string, string>();
  const serverVersions = new Map<string, string>();
  const lspToolNames = new Set(["lsp_go_to_definition", "lsp_type_definition", "lsp_implementation", "lsp_find_references", "lsp_hover", "lsp_document_symbols", "lsp_enclosing_symbol", "lsp_workspace_symbols", "lsp_diagnostics", "lsp_context", "lsp_prepare_edit_context", "lsp_incoming_calls", "lsp_outgoing_calls", "lsp_code_actions", "lsp_package_context"]);
  const toolStarts = new Map<string, number>();
  const lspPromotedGuidelines = [
    "Use rg/read for broad text discovery; use lsp_context after locating a Go, TypeScript, YAML, or Helm file position to get semantic context before editing.",
    "Use lsp_go_to_definition or lsp_find_references when following a known symbol; use lsp_diagnostics after edits or when investigating type/schema errors.",
  ];
  type ToolStats = { calls: number; successes: number; empty: number; errors: number; totalMs: number };
  const metrics = { tools: new Map<string, ToolStats>(), followedLocations: 0, pendingFiles: new Map<string, Set<string>>(), lastTouched: [] as string[] };
  const targetPrefix = resolvePath("~/.pi/agent/extensions", "/");
  const sourcePrefix = resolvePath("dot_pi/agent/exact_extensions", cwdFn());

  pi.on("session_start", async (_event, ctx) => { for (const entry of ctx.sessionManager.getBranch()) if (entry.type === "custom" && entry.customType === "lsp-state") { const data = entry.data as LspState | undefined; for (const [k, v] of Object.entries(data?.workspaceRoots ?? {})) if (typeof k === "string" && typeof v === "string") workspaceRoots.set(k, v); for (const [k, v] of Object.entries(data?.serverVersions ?? {})) if (typeof k === "string" && typeof v === "string") serverVersions.set(k, v); } });
  pi.on("tool_execution_start", async (event) => { if (lspToolNames.has(event.toolName)) { ensureToolStats(event.toolName).calls++; toolStarts.set(event.toolCallId, Date.now()); } else recordFollowedLocation(event.toolName, [event.args, event]); });
  pi.on("tool_result", async (event) => { if (lspToolNames.has(event.toolName)) recordLspResult(event.toolName, event.isError, event.content, event.details); else recordFollowedLocation(event.toolName, [event.input, event]); });
  pi.on("tool_execution_end", async (event) => { if (lspToolNames.has(event.toolName)) { const started = toolStarts.get(event.toolCallId); if (started) ensureToolStats(event.toolName).totalMs += Date.now() - started; toolStarts.delete(event.toolCallId); } });
  pi.on("session_shutdown", async () => { persistMetrics(); await Promise.all([...clients.values()].map((c) => c.shutdown().catch(() => undefined))); });
  function persistState() { pi.appendEntry<LspState>("lsp-state", { workspaceRoots: Object.fromEntries(workspaceRoots), serverVersions: Object.fromEntries(serverVersions) }); }
  function ensureToolStats(toolName: string): ToolStats { const stats = metrics.tools.get(toolName) ?? { calls: 0, successes: 0, empty: 0, errors: 0, totalMs: 0 }; metrics.tools.set(toolName, stats); return stats; }
  function resultText(content: unknown): string { return Array.isArray(content) ? content.map((item) => typeof item === "object" && item && "text" in item ? String((item as { text?: unknown }).text ?? "") : "").join("\n") : ""; }
  function candidatePaths(path: string): string[] { const cleaned = path.replace(/^\.\//, ""); const resolved = resolvePath(cleaned, cwdFn()); const candidates = new Set([cleaned, resolved]); if (cleaned.startsWith("exact_extensions/")) { candidates.add(resolvePath(cleaned.replace(/^exact_extensions\//, "dot_pi/agent/exact_extensions/"), cwdFn())); candidates.add(resolvePath(cleaned, targetPrefix)); } if (resolved.startsWith(targetPrefix)) candidates.add(resolvePath(resolved.slice(targetPrefix.length + 1), sourcePrefix)); if (resolved.startsWith(sourcePrefix)) candidates.add(resolvePath(resolved.slice(sourcePrefix.length + 1), targetPrefix)); return [...candidates]; }
  function collectPaths(value: unknown, paths = new Set<string>()): Set<string> { if (!value) return paths; if (typeof value === "string") { if (value.startsWith("/") || value.startsWith("file://") || value.startsWith("./") || value.startsWith("dot_pi/") || value.startsWith("exact_extensions/")) for (const path of candidatePaths(value.startsWith("file://") ? uriToPath(value) : value)) paths.add(path); return paths; } if (Array.isArray(value)) { for (const item of value) collectPaths(item, paths); return paths; } if (typeof value === "object") for (const nested of Object.values(value)) collectPaths(nested, paths); return paths; }
  function collectLocationTextPaths(text: string): Set<string> { return new Set([...text.matchAll(/(?:^|\n)([^\n:]+):(\d+):(\d+)/g)].flatMap((match) => candidatePaths(match[1].trim()))); }
  function recordLspResult(toolName: string, isError: boolean | undefined, content: unknown, details: unknown) { const stats = ensureToolStats(toolName); const text = resultText(content); const lowerText = text.toLowerCase(); if (isError || lowerText.includes("error:") || lowerText.includes("not found on path") || lowerText.includes("unsupported file type")) stats.errors++; else if (lowerText.startsWith("no ") || lowerText.includes("\nnone") || lowerText.includes("no diagnostics collected")) stats.empty++; else stats.successes++; const paths = collectPaths(details); for (const path of collectLocationTextPaths(text)) paths.add(path); if (paths.size) metrics.pendingFiles.set(toolName, paths); }
  function recordFollowedLocation(toolName: string, input: unknown) { if (!["read", "edit", "write"].includes(toolName)) return; const touched = collectPaths(input); metrics.lastTouched = [...touched].slice(0, 5); if (!touched.size) return; for (const [, paths] of metrics.pendingFiles) for (const touchedPath of touched) for (const lspPath of paths) if (touchedPath === lspPath || touchedPath.endsWith(lspPath) || lspPath.endsWith(touchedPath)) { metrics.followedLocations++; metrics.pendingFiles.clear(); return; } }
  function persistMetrics() { if (![...metrics.tools.values()].some((stats) => stats.calls > 0)) return; pi.appendEntry("lsp-metrics", { tools: Object.fromEntries(metrics.tools), followedLocations: metrics.followedLocations, timestamp: new Date().toISOString() }); }
  function metricsText(): string { const lines = [...metrics.tools.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([tool, stats]) => `- ${tool}: calls=${stats.calls} success=${stats.successes} empty=${stats.empty} errors=${stats.errors} avgMs=${stats.calls ? Math.round(stats.totalMs / stats.calls) : 0}`); const pending = [...metrics.pendingFiles.values()].flatMap((paths) => [...paths]).slice(0, 5); return [`LSP metrics:`, lines.join("\n") || "- no LSP calls recorded this session", `Followed locations: ${metrics.followedLocations}`, `Pending paths: ${pending.join(", ") || "none"}`, `Last touched: ${metrics.lastTouched.join(", ") || "none"}`].join("\n"); }
  function configForRoot(filePath: string, config: ServerConfig, root: string): ServerConfig { const match = config.workspaceOverrides?.find((o) => findAncestorWithMarker(filePath, o.rootMarker) === root); return match ? { ...config, command: match.command ?? config.command, args: match.args ?? config.args, env: { ...(config.env ?? {}), ...(match.env ?? {}) }, initializationOptions: match.initializationOptions ?? config.initializationOptions, activeOverride: match.name ?? match.rootMarker } : config; }
  function rootForFile(filePath: string, config: ServerConfig): string { const override = workspaceRoots.get(config.id); if (override && isInsidePath(filePath, override)) return override; for (const o of config.workspaceOverrides ?? []) { const root = findAncestorWithMarker(filePath, o.rootMarker); if (root) return o.root ? o.root(filePath, root) : root; } return findWorkspaceRoot(filePath, config); }
  function resolveFile(file: string) { const abs = resolvePath(file, cwdFn()); if (!existsSync(abs)) throw new Error(`file does not exist: ${abs}`); const baseConfig = configForFile(abs, SERVER_CONFIGS); if (!baseConfig) throw new Error(`unsupported file type: ${abs}`); const root = rootForFile(abs, baseConfig); const config = configForRoot(abs, baseConfig, root); return { filePath: abs, config, root }; }
  function installHint(config: ServerConfig): string { return ["typescript", "yaml", "helm"].includes(config.id) ? ` with: brew install ${config.id === "helm" ? "helm-ls" : config.id === "yaml" ? "yaml-language-server" : "typescript-language-server"}` : ""; }
  async function ensureClient(config: ServerConfig, root: string): Promise<LspClient> { const key = `${config.id}:${root}`; const existing = clients.get(key); if (existing?.isRunning && existing.isInitialized) return existing; const starting = startingClients.get(key); if (starting) return starting; const promise = (async () => { const commandPath = findExecutable(config.command); if (!commandPath) throw new Error(`${config.label} language server not found on PATH. Install ${config.command}${installHint(config)}`); const current = clients.get(key); if (current) await current.shutdown().catch(() => undefined); const client = new LspClient(root, config, commandPath); const info = await client.start(); clients.set(key, client); if (info.serverInfo?.version) serverVersions.set(config.id, info.serverInfo.version); persistState(); return client; })().finally(() => startingClients.delete(key)); startingClients.set(key, promise); return promise; }
  async function fileClient(file: string) { const r = resolveFile(file); return { ...r, client: await ensureClient(r.config, r.root) }; }
  function workspaceSymbolsTarget(file?: string): { config: ServerConfig; root: string } {
    if (file) return resolveFile(file);
    const running = [...clients.keys()];
    if (running.length === 1) {
      const [id, ...rootParts] = running[0].split(":");
      const config = SERVER_CONFIGS.find((c) => c.id === id);
      if (config) return { config, root: rootParts.join(":") };
    }
    throw new Error(running.length ? "multiple LSP clients are running; pass file to choose language/root" : "pass file to choose language/root; no LSP clients are running yet");
  }
  function statusText(): string {
    const clientLines = [...clients.entries()].map(([key, client]) => {
      const state = client.debugState();
      const [id] = key.split(":");
      const version = serverVersions.get(id) ?? "unknown";
      return `- ${key} running=${state.running} initialized=${state.initialized} command=${state.command} commandPath=${state.commandPath} args=${state.args.join(" ")} override=${state.activeOverride ?? "none"} env=${Object.entries(state.env).map(([k, v]) => `${k}=${v}`).join(",") || "none"} openDocs=${state.openDocuments} diagnostics=${state.diagnostics} syncing=${state.syncingDocuments} version=${version}`;
    });
    const rootLines = [...workspaceRoots.entries()].map(([k, v]) => `- ${k}=${v}`);
    return [`LSP clients (${clients.size}):`, clientLines.join("\n") || "- none", "Roots:", rootLines.join("\n") || "- auto"].join("\n");
  }

  async function richLocationResult(name: string, label: string, params: { file: string; line: number; column: number }, get: (c: LspClient, filePath: string) => Promise<Location[]>) { try { const { client, filePath, root } = await fileClient(params.file); const locations = await get(client, filePath); return locations.length ? { content: [{ type: "text" as const, text: `${label} found:\n${locations.map((loc) => `${formatLocation(loc, root)}${linePreview(uriToPath(loc.uri), loc.range.start.line + 1, 1) ? `\n  ${linePreview(uriToPath(loc.uri), loc.range.start.line + 1, 1)}` : ""}`).join("\n")}` }], details: { locations: locationsDetails(locations) } } : { content: [{ type: "text" as const, text: `No ${label.toLowerCase()} found at ${params.file}:${params.line}:${params.column}` }], details: { locations: [] } }; } catch (err) { return errorResult(name, err); } }
  async function contextResult(name: string, params: { file: string; line: number; column: number; includeReferences?: boolean; includeDiagnostics?: boolean }, signal?: AbortSignal) { try { const { client, filePath, root, config } = await fileClient(params.file); const [hover, definitions, symbols] = await Promise.all([client.hover(filePath, params.line, params.column, signal), client.goToDefinition(filePath, params.line, params.column, signal), client.documentSymbols(filePath, signal)]); const references = params.includeReferences ? await client.findReferences(filePath, params.line, params.column, signal) : []; const diagnostics = params.includeDiagnostics === false ? new Map<string, Diagnostic[]>() : client.diagnostics(filePath); const enclosing = findEnclosingSymbol(symbols, params.line, params.column); const pkg = config.packageContext?.(filePath, root, symbols, diagnostics); const text = [`Language: ${config.label}`, `Hover:\n${hover || "none"}`, `Definition:\n${definitions.map((loc) => formatLocation(loc, root)).join("\n") || "none"}`, `Enclosing:\n${enclosing ? formatSymbol(enclosing) : "none"}`, `References: ${references.length}`, `Diagnostics: ${diagnosticsDetails(diagnostics).length}`].join("\n\n"); return { content: [{ type: "text" as const, text }], details: { language: config.id, hover, definitions: locationsDetails(definitions), enclosing: enclosing ? { name: enclosing.name, kind: symbolKindName(enclosing.kind), range: rangeToDetails(enclosing.range) } : null, references: locationsDetails(references), diagnostics: diagnosticsDetails(diagnostics), package: pkg, symbols: flattenSymbols(symbols).map((s) => ({ name: s.name, kind: symbolKindName(s.kind), range: rangeToDetails(s.range) })) } }; } catch (err) { return errorResult(name, err); } }
  const contextParams = Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer(), includeReferences: Type.Optional(Type.Boolean()), includeDiagnostics: Type.Optional(Type.Boolean()) });

  pi.registerTool({ name: "lsp_go_to_definition", label: "Go to Definition", description: "Find where a symbol is defined using the file's language server.", promptSnippet: "Follow a known Go/TypeScript/YAML/Helm symbol from a file/line/column to its definition.", promptGuidelines: lspPromotedGuidelines, parameters: Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer() }), async execute(_id, params, signal) { return richLocationResult("lsp_go_to_definition", "Definition", params, (c, f) => c.goToDefinition(f, params.line, params.column, signal)); } });
  pi.registerTool({ name: "lsp_type_definition", label: "Type Definition", description: "Find a symbol's type definition using the file's language server.", parameters: Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer() }), async execute(_id, params, signal) { return richLocationResult("lsp_type_definition", "Type definition", params, (c, f) => c.typeDefinition(f, params.line, params.column, signal)); } });
  pi.registerTool({ name: "lsp_implementation", label: "Implementation", description: "Find implementations using the file's language server.", parameters: Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer() }), async execute(_id, params, signal) { return richLocationResult("lsp_implementation", "Implementation", params, (c, f) => c.implementation(f, params.line, params.column, signal)); } });
  pi.registerTool({ name: "lsp_find_references", label: "Find References", description: "Find all references to a symbol using the file's language server.", promptSnippet: "Find semantic references to a known Go/TypeScript/YAML/Helm symbol from a file/line/column.", promptGuidelines: lspPromotedGuidelines, parameters: Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer() }), async execute(_id, params, signal) { try { const { client, filePath, root } = await fileClient(params.file); const locations = await client.findReferences(filePath, params.line, params.column, signal); return locations.length ? { content: [{ type: "text" as const, text: `References found (${locations.length}):\n${locations.map((loc) => formatLocation(loc, root)).join("\n")}` }], details: { locations: locationsDetails(locations) } } : { content: [{ type: "text" as const, text: `No references found at ${params.file}:${params.line}:${params.column}` }], details: { locations: [] } }; } catch (err) { return errorResult("lsp_find_references", err); } } });
  pi.registerTool({ name: "lsp_hover", label: "LSP Hover", description: "Get type information and documentation for a symbol.", parameters: Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer() }), async execute(_id, params, signal) { try { const { client, filePath } = await fileClient(params.file); const text = await client.hover(filePath, params.line, params.column, signal); return { content: [{ type: "text" as const, text: text || `No hover information at ${params.file}:${params.line}:${params.column}` }], details: {} }; } catch (err) { return errorResult("lsp_hover", err); } } });
  pi.registerTool({ name: "lsp_document_symbols", label: "Document Symbols", description: "List all symbols in a file using its language server.", parameters: Type.Object({ file: Type.String() }), async execute(_id, params, signal) { try { const { client, filePath } = await fileClient(params.file); const symbols = await client.documentSymbols(filePath, signal); return symbols.length ? { content: [{ type: "text" as const, text: `Symbols in ${params.file}:\n${formatSymbols(symbols).join("\n")}` }], details: { symbols: flattenSymbols(symbols).map((s) => ({ name: s.name, kind: symbolKindName(s.kind), range: rangeToDetails(s.range) })) } } : { content: [{ type: "text" as const, text: `No symbols found in ${params.file}` }], details: { symbols: [] } }; } catch (err) { return errorResult("lsp_document_symbols", err); } } });
  pi.registerTool({ name: "lsp_enclosing_symbol", label: "Enclosing Symbol", description: "Return the smallest symbol containing a file position.", parameters: Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer() }), async execute(_id, params, signal) { try { const { client, filePath } = await fileClient(params.file); const symbol = findEnclosingSymbol(await client.documentSymbols(filePath, signal), params.line, params.column); return symbol ? { content: [{ type: "text" as const, text: `Enclosing symbol: ${formatSymbol(symbol)}` }], details: { name: symbol.name, kind: symbolKindName(symbol.kind), range: rangeToDetails(symbol.range), selectionRange: rangeToDetails(symbol.selectionRange) } } : { content: [{ type: "text" as const, text: `No enclosing symbol found at ${params.file}:${params.line}:${params.column}` }], details: {} }; } catch (err) { return errorResult("lsp_enclosing_symbol", err); } } });
  pi.registerTool({ name: "lsp_workspace_symbols", label: "Workspace Symbols", description: "Search symbols across the language workspace inferred from an optional file.", parameters: Type.Object({ query: Type.String(), file: Type.Optional(Type.String()) }), async execute(_id, params, signal) { try { const target = workspaceSymbolsTarget(params.file); const client = await ensureClient(target.config, target.root); const symbols = await client.workspaceSymbols(params.query, signal); const shown = symbols.slice(0, 50); return symbols.length ? { content: [{ type: "text" as const, text: `Workspace symbols matching "${params.query}" (${symbols.length} found, showing first ${shown.length}):\n${shown.map((s) => `${symbolKindName(s.kind)} ${s.name}${s.containerName ? ` (${s.containerName})` : ""} — ${relativePath(uriToPath(s.location.uri), target.root)}:${s.location.range.start.line + 1}`).join("\n")}` }], details: { symbols: shown.map((s) => ({ name: s.name, kind: symbolKindName(s.kind), path: uriToPath(s.location.uri), line: s.location.range.start.line + 1, preview: linePreview(uriToPath(s.location.uri), s.location.range.start.line + 1, 1) })) } } : { content: [{ type: "text" as const, text: `No workspace symbols found matching "${params.query}"` }], details: { symbols: [] } }; } catch (err) { return errorResult("lsp_workspace_symbols", err); } } });
  pi.registerTool({ name: "lsp_diagnostics", label: "Diagnostics", description: "Return diagnostics collected from opened files. Pass file to choose language/root.", promptSnippet: "Check language-server diagnostics for an opened or specified Go/TypeScript/YAML/Helm file.", promptGuidelines: lspPromotedGuidelines, parameters: Type.Object({ file: Type.Optional(Type.String()) }), async execute(_id, params) { try { if (params.file) { const { client, filePath, root } = await fileClient(params.file); await client.openDocument(filePath); await client.waitForDiagnostics(filePath); const map = client.diagnostics(filePath); const items = [...map.entries()].flatMap(([path, diagnostics]) => diagnostics.map((diagnostic) => ({ path, diagnostic }))); return items.length ? { content: [{ type: "text" as const, text: `Diagnostics (${items.length}):\n${formatDiagnostics(items, root).join("\n")}` }], details: { diagnostics: diagnosticsDetails(map) } } : { content: [{ type: "text" as const, text: `No diagnostics for ${params.file}` }], details: { diagnostics: [] } }; } const all = [...clients.entries()].flatMap(([key, c]) => [...c.diagnostics().entries()].map(([path, diagnostics]) => ({ key, path, diagnostics }))); return { content: [{ type: "text" as const, text: all.length ? all.flatMap(({ path, diagnostics }) => diagnostics.map((d) => `${path}:${d.range.start.line + 1}:${d.range.start.character + 1} ${d.message}`)).join("\n") : "No diagnostics collected. Open files with LSP tools first." }], details: { diagnostics: all } }; } catch (err) { return errorResult("lsp_diagnostics", err); } } });
  pi.registerTool({ name: "lsp_context", label: "LSP Context", description: "Collect hover, definition, enclosing symbol, document symbols, diagnostics, package context, and optional references for a position.", promptSnippet: "Best default LSP tool once a Go/TypeScript/YAML/Helm file/line/column is known; returns type, definition, enclosing symbol, diagnostics, and package context.", promptGuidelines: lspPromotedGuidelines, parameters: contextParams, async execute(_id, params, signal) { return contextResult("lsp_context", params, signal); } });
  pi.registerTool({ name: "lsp_prepare_edit_context", label: "Prepare Edit Context", description: "Alias of lsp_context kept for compatibility.", parameters: contextParams, async execute(_id, params, signal) { return contextResult("lsp_prepare_edit_context", params, signal); } });
  pi.registerTool({ name: "lsp_incoming_calls", label: "Incoming Calls", description: "Find callers of the symbol at a position.", parameters: Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer() }), async execute(_id, params, signal) { try { const { client, filePath, root } = await fileClient(params.file); const items = await client.prepareCallHierarchy(filePath, params.line, params.column, signal); const calls = items.length ? await client.incomingCalls(items[0], signal) : []; return calls.length ? { content: [{ type: "text" as const, text: `Incoming calls (${calls.length}):\n${calls.map((call) => `${call.from.name} — ${formatLocation({ uri: call.from.uri, range: call.from.selectionRange }, root)}`).join("\n")}` }], details: { calls } } : { content: [{ type: "text" as const, text: `No incoming calls found at ${params.file}:${params.line}:${params.column}` }], details: { calls: [] } }; } catch (err) { return errorResult("lsp_incoming_calls", err); } } });
  pi.registerTool({ name: "lsp_outgoing_calls", label: "Outgoing Calls", description: "Find calls made by the symbol at a position.", parameters: Type.Object({ file: Type.String(), line: Type.Integer(), column: Type.Integer() }), async execute(_id, params, signal) { try { const { client, filePath, root } = await fileClient(params.file); const items = await client.prepareCallHierarchy(filePath, params.line, params.column, signal); const calls = items.length ? await client.outgoingCalls(items[0], signal) : []; return calls.length ? { content: [{ type: "text" as const, text: `Outgoing calls (${calls.length}):\n${calls.map((call) => `${call.to.name} — ${formatLocation({ uri: call.to.uri, range: call.to.selectionRange }, root)}`).join("\n")}` }], details: { calls } } : { content: [{ type: "text" as const, text: `No outgoing calls found at ${params.file}:${params.line}:${params.column}` }], details: { calls: [] } }; } catch (err) { return errorResult("lsp_outgoing_calls", err); } } });
  pi.registerTool({ name: "lsp_code_actions", label: "Code Actions", description: "List LSP code actions for a file/range. Preview only; does not apply edits.", parameters: Type.Object({ file: Type.String(), startLine: Type.Optional(Type.Integer()), startColumn: Type.Optional(Type.Integer()), endLine: Type.Optional(Type.Integer()), endColumn: Type.Optional(Type.Integer()) }), async execute(_id, params, signal) { try { const { client, filePath } = await fileClient(params.file); const range = { start: toLspPosition(params.startLine ?? 1, params.startColumn ?? 1), end: toLspPosition(params.endLine ?? params.startLine ?? 1, params.endColumn ?? params.startColumn ?? 1) }; const actions = await client.codeActions(filePath, range, client.diagnostics(filePath).get(filePath) ?? [], signal); return actions.length ? { content: [{ type: "text" as const, text: `Code actions (${actions.length}):\n${actions.map((a, i) => `${i + 1}. ${a.title}${a.kind ? ` [${a.kind}]` : ""}${a.edit ? " (has edit)" : ""}`).join("\n")}` }], details: { actions: actions.map((a, i) => ({ index: i + 1, title: a.title, kind: a.kind, hasEdit: Boolean(a.edit), hasCommand: Boolean(a.command), diagnostics: a.diagnostics?.map((d) => d.message) ?? [] })) } } : { content: [{ type: "text" as const, text: `No code actions for ${params.file}` }], details: { actions: [] } }; } catch (err) { return errorResult("lsp_code_actions", err); } } });
  pi.registerTool({ name: "lsp_package_context", label: "Package Context", description: "Return language package/module context for a file.", parameters: Type.Object({ file: Type.String() }), async execute(_id, params, signal) { try { const { client, filePath, root, config } = await fileClient(params.file); const symbols = await client.documentSymbols(filePath, signal); const diagnostics = client.diagnostics(filePath); const pkg = config.packageContext?.(filePath, root, symbols, diagnostics) ?? {}; return { content: [{ type: "text" as const, text: `${config.label} context\nDir: ${relativePath(dirname(filePath), root)}\nDiagnostics: ${diagnosticsDetails(diagnostics).length}` }], details: pkg }; } catch (err) { return errorResult("lsp_package_context", err); } } });

  pi.registerCommand("lsp", { description: "LSP status/control. Usage: /lsp [status|metrics|restart|stop|root <language> [path]]", handler: async (args, ctx) => { const [action = "status", lang, ...rest] = (args || "status").trim().split(/\s+/); switch (action.toLowerCase()) { case "status": ctx.ui.notify(statusText(), "info"); break; case "metrics": ctx.ui.notify(metricsText(), "info"); break; case "restart": await Promise.all([...clients.values()].map((c) => c.shutdown().catch(() => undefined))); clients.clear(); ctx.ui.notify("LSP clients stopped; they restart on next tool call", "success"); break; case "stop": await Promise.all([...clients.values()].map((c) => c.shutdown().catch(() => undefined))); clients.clear(); ctx.ui.notify("LSP clients stopped", "info"); break; case "root": { const config = SERVER_CONFIGS.find((c) => c.id === lang); if (!config) { ctx.ui.notify(`Unknown language: ${lang}. Known: ${SERVER_CONFIGS.map((c) => c.id).join(", ")}`, "error"); break; } const next = rest.join(" "); if (!next) { ctx.ui.notify(`${config.label} root: ${workspaceRoots.get(config.id) ?? "auto"}`, "info"); break; } workspaceRoots.set(config.id, findWorkspaceRoot(resolvePath(next, cwdFn()), config)); for (const [key, c] of clients) if (key.startsWith(`${config.id}:`)) { await c.shutdown().catch(() => undefined); clients.delete(key); } persistState(); ctx.ui.notify(`${config.label} root set to ${workspaceRoots.get(config.id)}`, "success"); break; } default: ctx.ui.notify(`Unknown action: ${action}. Usage: /lsp [status|metrics|restart|stop|root <language> [path]]`, "error"); } } });
}
